spring.application.name=demo
spring.mail.host=smtp.gmail.com  
spring.mail.port=587  
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=true  
spring.mail.properties.mail.smtp.starttls.enable=true  

app.user.username=mrfox2344
app.user.password=mrfox2344
app.user.name=Jane doe

app.admin.username=eoscria
app.admin.password=eoscria
app.admin.name=John Doe